# Generated by Django 3.0 on 2020-01-08 22:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 22, 3, 37, 600708, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
